# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'BKReduxApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BKReduxApp
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  
  target 'BKReduxAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
