# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'BKReduxApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BKReduxApp
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  
  target 'BKReduxAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'RxSwift'
              target.build_configurations.each do |config|
                  if config.name == 'Debug' || config.name == 'StagingDebug' || config.name == 'ProductionDebug'
                      config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-D', 'TRACE_RESOURCES']
                  end
              end
          end
      end
  end

end
